# Generated by Django 2.0 on 2018-03-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passenger_reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.BigIntegerField()),
                ('coach_no', models.CharField(max_length=4)),
                ('seat_no', models.CharField(max_length=4)),
                ('passenger_name', models.CharField(max_length=20)),
                ('passenger_age', models.IntegerField(default='', max_length=4)),
                ('gender', models.CharField(choices=[('Male', 'O'), ('Female', 'F'), ('Others', 'O')], default='Male', max_length=1)),
                ('contact_no', models.BigIntegerField()),
                ('ticket_status', models.CharField(choices=[('Available_02', 'Available 01'), ('Available_01', 'Available 02'), ('Reservation_against_cancellation_01', 'RAC 01'), ('Reservation_against_cancellation_02', 'RAC 02'), ('Reservation_against_cancellation_03', 'RAC 03'), ('Reservation_against_cancellation_04', 'RAC 04'), ('Waiting_list_01', 'WL 01'), ('Waiting_list_02', 'WL 02')], default='Available_02', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.IntegerField()),
                ('train_name', models.CharField(default='', max_length=60)),
                ('route_origin_code', models.CharField(default='', max_length=5)),
                ('route_destination_code', models.CharField(default='', max_length=5)),
                ('region', models.CharField(max_length=3)),
            ],
        ),
    ]
