# Generated by Django 2.0 on 2018-03-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stopages_station',
            fields=[
                ('station_code', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('station_name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='id',
        ),
        migrations.AddField(
            model_name='passenger_reservation',
            name='train_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DTC.Train'),
        ),
        migrations.AddField(
            model_name='passenger_reservation',
            name='verification_status',
            field=models.CharField(choices=[('P', 'Pending'), ('U', 'Unallocated'), ('V', 'Verified')], default='Pending', max_length=1),
        ),
        migrations.AddField(
            model_name='train',
            name='no_of_stopages',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='passenger_reservation',
            name='coach_no',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='passenger_reservation',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='Male', max_length=1),
        ),
        migrations.AlterField(
            model_name='passenger_reservation',
            name='passenger_age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='passenger_reservation',
            name='seat_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='passenger_reservation',
            name='boarding_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DTC.stopages_station'),
        ),
    ]
