# Generated by Django 2.0 on 2018-03-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTC', '0002_auto_20180306_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='stopages_list',
            field=models.ManyToManyField(to='DTC.stopages_station'),
        ),
    ]
