# Generated by Django 2.0 on 2018-03-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTC', '0003_train_stopages_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='route_destination_code',
        ),
        migrations.RemoveField(
            model_name='train',
            name='route_origin_code',
        ),
    ]
