# Generated by Django 2.0 on 2018-03-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTC', '0004_auto_20180306_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='route_destination_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='train',
            name='route_origin_code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
