# Generated by Django 2.0 on 2018-03-23 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DTC', '0005_auto_20180306_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_Info',
            fields=[
                ('tc_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='passenger_reservation',
            name='destination_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upto_station', to='DTC.stopages_station'),
        ),
        migrations.AlterField(
            model_name='passenger_reservation',
            name='boarding_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boarding_station', to='DTC.stopages_station'),
        ),
    ]
