# Generated by Django 2.0 on 2018-03-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTC', '0006_auto_20180323_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_reservation',
            name='seat_no',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='passenger_reservation',
            name='ticket_status',
            field=models.CharField(choices=[('Available 01', 'Available_01'), ('Available 02', 'Available_02'), ('RAC 01', 'Reservation_against_cancellation_01'), ('RAC 02', 'Reservation_against_cancellation_02'), ('RAC 03', 'Reservation_against_cancellation_03'), ('RAC 04', 'Reservation_against_cancellation_04'), ('WL 01', 'Waiting_list_01'), ('WL 02', 'Waiting_list_02')], default='Available_01', max_length=15, null=True),
        ),
    ]
